name: Python Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'gemini/**'
      - '.github/workflows/apimtest.yml'
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Dev 
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Create .env file
      run: |
        echo "GEMINI_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > gemini/.env
        echo "AZURE_APIM_ENDPOINT=${{ vars.AZURE_API_URL }}" >> gemini/.env
        echo "AZURE_APIM_SUBSCRIPTION_KEY=${{ secrets.AZURE_API_KEY }}" >> gemini/.env
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai python-dotenv requests
        
    - name: Run tests
      run: |
        cd gemini
        python -m unittest test.py -v